apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: netbird-default-scopes
spec:
  forProvider:
    defaultScopes:
      - acr
      - email
      - profile
      - roles
      - web-origins
      - netbird-api
    clientIdRef:
      name: netbird
    realmIdRef:
      name: homelab
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  name: netbird-api
spec:
  forProvider:
    name: netbird-api
    consentScreenText: Netbird Management API
    includeInTokenScope: true
    realmIdRef:
      name: homelab
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: netbird-api-audience-mapper
spec:
  forProvider:
    name: Audience for NetBird Management API
    protocol: openid-connect
    protocolMapper: oidc-audience-mapper
    config:
      included.client.audience: "netbird"
      id.token.claim: "false"
      access.token.claim: "true"
      introspection.token.claim: "true"
      userinfo.token.claim: "false"
    clientScopeIdRef:
      name: netbird-api
    realmIdRef:
      name: homelab
