apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  storageClassName: plex-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
spec:
  storageClassName: media-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.8Ti