apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: plex-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer