apiVersion: v1
kind: Service
metadata:
  namespace: plex
  name: plex
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 32400
    - name: a
      port: 1900
      protocol: UDP
    - name: b
      port: 3005
    - name: c
      port: 8324
    - name: d
      port: 32410
      protocol: UDP
    - name: e
      port: 32412
      protocol: UDP
    - name: f
      port: 32413
      protocol: UDP
    - name: g
      port: 32414
      protocol: UDP
    - name: h
      port: 32469
  selector:
    app: plex