apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr

resources:
  - namespace.yaml
  - ingress.yaml
  - traefik-forward-auth
  - qbittorrent
  - prowlarr
  - sonarr
  - radarr
  - lidarr
