apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media
  namespace: argocd
  labels:
    dev.stonegarden: media
spec:
  generators:
    - git:
        repoURL: https://github.com/vehagn/homelab
        revision: HEAD
        directories:
          - path: apps/media/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: media
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/vehagn/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
