apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: cnpg-database
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
      additional:
        - selectorType: rw
          updateStrategy: patch
          serviceTemplate:
            metadata:
              name: cluster-example-ext
              annotations:
                io.cilium/lb-ipam-ips: 192.168.1.231
            spec:
              type: LoadBalancer
  storage:
    storageClass: proxmox-csi
    size: 4G
