apiVersion: v1
kind: Service
metadata:
  namespace: arr
  name: qbittorrent
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8112
    - name: a
      port: 11010
      protocol: TCP
    - name: b
      port: 11011
      protocol: TCP
    - name: c
      port: 11012
      protocol: TCP
    - name: d
      port: 11013
      protocol: TCP
    - name: e
      port: 11014
      protocol: TCP
    - name: f
      port: 11015
      protocol: TCP
    - name: a1
      port: 11010
      protocol: UDP
    - name: b1
      port: 11011
      protocol: UDP
    - name: c1
      port: 11012
      protocol: UDP
    - name: d1
      port: 11013
      protocol: UDP
    - name: e1
      port: 11014
      protocol: UDP
    - name: f1
      port: 11015
      protocol: UDP
  selector:
    app: qbittorrent