apiVersion: v1
kind: ConfigMap
metadata:
  name: device-plugin-time-slicing
  namespace: gpu-operator
data:
  any: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 10