apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
  namespace: netbird
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: relay
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: docker.io/netbirdio/relay:0.36.3 # renovate: docker=netbirdio/relay
          imagePullPolicy: IfNotPresent
          name: relay
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              drop: [ ALL ]
              add: [ NET_ADMIN, NET_RAW, PERFMON, BPF ]
          envFrom:
            - configMapRef:
                name: relay-config
            - secretRef:
                name: relay-secret
          ports:
            - containerPort: 80
              name: relay
              protocol: TCP
          resources:
            requests:
              memory: 16Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 4000m