apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: netbird
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: relay
  ports:
    - name: relay
      port: 80
      targetPort: relay
