apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: grafana
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgA1xCPus0KtKXyt1nQdKfp3VYE5i7cFI2uF4FMTicTXJk3yIA23zJsFL3/4bTpr2gM0VZMGlzYUwIlG9FjpnGlqrEVaxytL6D4ot/77rrTbSER3EdQXSne+wQKkxZ/s9fVmu8NjPmOuXUkG9QwqgboLSyYfEW9w++aUaokLJMg65sqq39y0Oz/gfhYvU7pLEXS1L644R//AG/J/kf4Wt89DaUse+I2JEBNrGTcypAPFpEzhQv5WW+qi62o4puzyQPwgDpwfzPdGnw1SYEWbkPxnKedSx8B3VhPibHLGAFsrV9e4sJeQ2zV+zouLrkDtQr9Cf2nWFwfrsXbKsSuYQfbEE4pF4D6Vhj7Ebum0vR1GOiMFDyhWVjyhaUQXkVwyCwV1+8tQDjJTg9yTLd4dHwte9f0vmVghjqib9Kb+tOAOoKpnfJBvy/Jv6IRN5P1NigQpFQcYjh31Uc3KZZt58Q0QXosynLWVBF0AUF+NBUNlwdpzoYsXbcAwKhuh06wZXF119B0yJ8mQPxXDO+cRuOOGz2ybTTomme4dgm3uSMgXVHXoLbQ71tfXTkBF2dqVfsbbGEHbRs7mGsefc6laozIcOtaiVRD8GS4yUkNGA5LlWRnNBXOlSuc3gak693eDDLh5cuirwh/9cU1jmf2mldwYs5zX56X1fspoyDxVlpZPcNRVAMJ0D9MsGegYzxro5DSUj3o0yb6Mori5rFV65Jqj21QkcpxfGF8Hpf3Zc1Wi3RfvojU=
    GF_SECURITY_ADMIN_USER: AgAEWEjN8X0qkvtR4AygwA8eS1Pi5bHcwdtq94lqtZvsWdDnUd1BNMmHn+8nobxq/LsyAZ62cQznVj5P5zmNdbC+KHWlHkxmEXOMgb2V7s0KPM5NKrgkz622jyk+jxKtLim6Hk2PK2wGFICVMdYfXij7DXizfeAtaGKujWUg89I4p0EtIRlwbuhclDD7OeBiwG91aJM2LD7je9x9BUGH+Sfsx6KUpPs/T+4sfB2Ijo6Rks9HurQRM5Y5zaJzn1qZ6HmufEU0cma/v+qBwXi4s5C6c7CKQPZB7B6diLIU2HTXtZwdY1edT9WqwWDBG5gmPT/mHxqAFXa5c6W2eAS+So+qAW/ZCTVt2YOW3fm69Warx86i1xeFwxV4mlquvC7DDkK8mOgSeJ23FpwmtqPg2mBlo35qGb+2QBtsuWFOV0mRz6aKW8haafNlYIltXWdhGsF1Shv2DT6n9FKgtQL7PcNMOKqy+KDOKG1yjUKrFfkd9iYN2Lp4gb/qtqpCzMZ9I9dKswu15c8sCfAvdGhgjjzxKNUbSHdwU3oPobHnLRku9nXQtYl2n85yW+kWPUrrJjYecFM2YKfiPubKuHSO8w6rWNGceDKhIVh1qHYZSausWwM0lC50QtuBUcHhgLvovzhcpXZGzFLa7BFkq+w2PZh/Di7PpXym51uQ0OoSy4ND1vNVNxeIUp1C+9xz6QskOBCvhmo7Qg==
  template:
    metadata:
      name: admin-credentials
      namespace: grafana
    type: Opaque
