apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  disableDefaultAdminSecret: true
  config:
    log:
      mode: console
    auth:
      disable_login_form: "false"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef: { name: admin-credentials }
