apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: adguard
spec:
  storageClassName: proxmox-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi