apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coturn

resources:
  - ns.yaml
  - secret-netbird-credentials.yaml

helmCharts:
  - name: coturn
    repo: https://charts.jaconi.io
    releaseName: coturn
    namespace: coturn
    version: 1.0.0
    valuesFile: values.yaml
