apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: management
  namespace: netbird
spec:
  encryptedData:
    datastoreEncryptionKey: AgDNMOtg45ztT8YA4MURhm3Bs5VhbApEMEwl6CWyW1GuDHXj6wsOA2hXIbqwrH6JoRyuZgapTTPtCTsMzOAq73OQ29iDiWtu+PLuNFnwCEGuByonxMH7niDv2V4q0P15+sAcqx/jB6l9FxLjioQJWaX9JPM2Qpt0kHFnXYV+phgZDXPJKkaaAFtYtzGdjLvOIIWWvpyXqg6bKaHkVGo29t1obcKMJRY2F1vlMEpwPtGhvA7T2jS7zZuZUJxIolVEz8iPQz5JGRZXzA2Qc6wYW0Vm6omLSrrpuJRF2GJ6CevKBxODJRvn2CMaw/CjZTjp/k/mVpDGkSJQA4+wErCbteCwbktGA11rDZxRmygvaPvyRlcmffSt8ZSXmeSUXRLPkIJXGPT3PJkeqxNnP6A1H6IMMLDWVMyk4z5RcN0IeACNbi8pMg2rQ8ecEXNAx4DCCjcYQs9qgyjexJg+WDAgDGmQ1TBlbXBk7m9nIUjkKUTBilBPEhXfZYF+VTC2OGmXIERmbBxkzRaXKWel10bqxvwGjWGXSo47mjw2i0qPNhG6REkGd/D+sMQ6ZUqyOz9ELs4XKnYP0vRcZLvLpDTMPMhG6wbiUoon1Bj6CRzy3vnVoRvhyv5cDEBGyqUa+MQmn/B01hSEcV74/t88XtqrINVmldcBf+/z5HXBBTGfNDghlhkasHEkDjJx3KNm78rJT09oV0Hn2X8d/WIqHYhUSC7j4kfpoauf99tD0fbDB4KKpCUU7Wd0XPnshOWKMA==
  template:
    metadata:
      name: management
      namespace: netbird
    type: Opaque
