FROM docker.io/docker:28.3.1-dind-alpine3.22

# Install required packages
RUN apk -U add \
    curl \
    bash \
    git \
    helm \
    kubectl \
    kustomize \
    make \
    opentofu \
    k9s \
    yq \
    jq \
    vim

RUN curl -sL https://talos.dev/install | sh

RUN adduser -s /bin/bash -D homelab -G docker
