FROM mcr.microsoft.com/devcontainers/base:alpine

# Install required packages
RUN apk -U add \
    curl \
    bash \
    git \
    helm \
    kubectl \
    kustomize \
    make \
    opentofu \
    k9s \
    yq \
    jq \
    openssl \
    vim

RUN curl -sL https://talos.dev/install | sh
