apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://dev.to/danielkun/kubernetes-certificates-tokens-authentication-and-service-accounts-4fj7
resources:
  - extra-admin.yaml
  - extra-admin-cluster-role-binding.yaml