#!/bin/bash
if [ "$3" -eq 1 ]; then
    # This hook is run after a checkout.
    # $1 is the ref of the previous HEAD
    # $2 is the ref of the new HEAD
    # $3 is a flag indicating if the checkout was a branch checkout (1) or a file checkout (0)
    echo "post-checkout hook: Branch changed. Creating refresh flag." >&2
    touch "$HOME/.needs_env_refresh"
fi
