apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http-route.yaml
  - dashboards/hubble.yaml
  - dashboards/hubble-dns-namespace.yaml
  - dashboards/hubble-l7-http-metrics.yaml
  - dashboards/hubble-network-overview.yaml
