apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: cloudflare
spec:
  deletionPolicy: Delete
  forProvider:
    name: Cloudflare
    accessType: CONFIDENTIAL
    clientId: cloudflare
    realmIdRef:
      name: homelab
    clientSecretSecretRef:
      name: cloudflare-oidc-credentials
      namespace: keycloak
      key: secret
    standardFlowEnabled: true
    baseUrl: "https://stonegarden.cloudflareaccess.com"
    validRedirectUris:
      - "https://stonegarden.cloudflareaccess.com/cdn-cgi/access/callback"
