apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts/
    version: 0.31.1
    namespace: intel-device-plugins
    releaseName: intel-device-plugins-gpu
    includeCRDs: true
    valuesFile: values.yaml
