apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-cmp-kustomize-build-with-helm
data:
  kustomize-build-with-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-build-with-helm
    spec:
      generate:
        command: [ "sh", "-c" ]
        args: [ "kustomize build --enable-helm" ]