name: Build devcontainer

on:
  push:
    branches: [ main ]
    paths: [ '.github/.devcontainer/**' ]
  schedule:
    - cron: '4 20 28 * *'

jobs:
  build:
    name: Build devcontainer
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev container image
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          subFolder: ./.github
          platform: linux/amd64,linux/arm64
          imageName: ghcr.io/vehagn/homelab-devcontainer
          cacheFrom: ghcr.io/vehagn/homelab-devcontainer
          push: always
